# PR open -> commit sample.diff
name: Update and commit sample.diff

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  update-samplediff:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Remove Unused Resouces
        run: |
          ./gradlew :sample:lintDebug :sample:removeUnusedResources -Prur.lint.onlyUnusedResources -Prur.lint.disableLintConfig -Prur.lintVariant="debug"
      - name: commit sample.diff
        shell: bash +e {0}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff > sample.diff
          git add sample.diff && git commit -m "Update sample.diff" && git push origin HEAD
          exit 0
